### ISSUE TITLE
Feature Request? 2 way communication between peers as well as to Master? Possible?

### ISSUE THREAD

**Issue by dannyz2** [Servayejc/esp_now_sender#1]
Is it possible to add 2 way communication between 2 “slaves” or “peers” in this scenario? I currently have a Master (Board 0), with 2 peers(Board 1 and Board 2). I would like to be able to have one of the peers (board 1) act the master function (Send and receive data from board2)to the second peer(Board 2), as it is very possible the “Master” might get out of range of the peers, and peer1 has a LCD Display that I would like to use to display data from peer2.

**Comment by Servayejc** [comment]
After the pairing is done, the server knows the MAC address off the peers, so each peers is able to post a message to the server for requesting the MAC address of the second peer. So, all the peers 1 and 2  can communicate directly: they are on the same channel.  in the function addPeer, you can create a list of peers with the peer number and the peer MAC address. you can send a message to the master to receive the MACAddress of any other peer.
